# Generated by Django 4.1.3 on 2023-02-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='gender',
            new_name='payment',
        ),
    ]
