# Generated by Django 4.1.3 on 2023-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
