# Generated by Django 4.1.3 on 2023-02-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='date',
        ),
    ]
