# Generated by Django 4.1.3 on 2023-02-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_products_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='select_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
