# Generated by Django 4.1.3 on 2023-02-13 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_productsmodel_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('UPI/NetBanking', 'UPI/NetBanking'), ('Pay with Debit/Credit/ATM Cards', 'Pay with Debit/Credit/ATM Cards'), ('Cash on Delivery', 'Cash on Delivery')], max_length=35)),
                ('product_buy', models.ManyToManyField(to='store.productsmodel')),
                ('user_buy', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
